import type { Match } from '../../matches/types/types';

export const mockKnockoutMatches: Match[] = [
  {
    id: '73',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Mexico',
    awayTeam: 'Switzerland',
    homeTeamCode: 'MEX',
    awayTeamCode: 'SUI',
    kickoff: '28 jun 2026, 12:00',
    kickoffAt: '2026-06-28T12:00:00Z',
    stadium: 'Mexico City Stadium',
    city: 'Mexico City',
    status: 'finished',
    displayOrder: 73,
    officialHomeScore: 2,
    officialAwayScore: 1,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'A',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'group_position',
    awaySourceGroupCode: 'B',
    awaySourceGroupRank: 2,
    awaySourceGroupSet: null,
    awaySourceMatchId: null
  },
  {
    id: '74',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Germany',
    awayTeam: 'Morocco',
    homeTeamCode: 'GER',
    awayTeamCode: 'MAR',
    kickoff: '28 jun 2026, 16:30',
    kickoffAt: '2026-06-28T16:30:00Z',
    stadium: 'Houston Stadium',
    city: 'Houston',
    status: 'finished',
    displayOrder: 74,
    officialHomeScore: 3,
    officialAwayScore: 0,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'E',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'best_third_place',
    awaySourceGroupCode: null,
    awaySourceGroupRank: 3,
    // homeSourceGroupSet: 'ABCDF',
    awaySourceGroupSet: 'ABCDF',
    awaySourceMatchId: null
  },
  {
    id: '75',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Brazil',
    awayTeam: 'USA',
    homeTeamCode: 'BRA',
    awayTeamCode: 'USA',
    kickoff: '29 jun 2026, 12:00',
    kickoffAt: '2026-06-29T12:00:00Z',
    stadium: 'Los Angeles Stadium',
    city: 'Los Angeles',
    status: 'finished',
    displayOrder: 75,
    officialHomeScore: 2,
    officialAwayScore: 0,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'C',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'group_position',
    awaySourceGroupCode: 'D',
    awaySourceGroupRank: 2,
    awaySourceGroupSet: null,
    awaySourceMatchId: null
  },
  {
    id: '76',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'England',
    awayTeam: 'Japan',
    homeTeamCode: 'ENG',
    awayTeamCode: 'JPN',
    kickoff: '29 jun 2026, 16:30',
    kickoffAt: '2026-06-29T16:30:00Z',
    stadium: 'Vancouver Stadium',
    city: 'Vancouver',
    status: 'finished',
    displayOrder: 76,
    officialHomeScore: 1,
    officialAwayScore: 0,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'F',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'best_third_place',
    awaySourceGroupCode: null,
    awaySourceGroupRank: 3,
    awaySourceGroupSet: 'BCEFH',
    awaySourceMatchId: null
  },
  {
    id: '77',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Argentina',
    awayTeam: 'Netherlands',
    homeTeamCode: 'ARG',
    awayTeamCode: 'NED',
    kickoff: '30 jun 2026, 12:00',
    kickoffAt: '2026-06-30T12:00:00Z',
    stadium: 'Miami Stadium',
    city: 'Miami',
    status: 'finished',
    displayOrder: 77,
    officialHomeScore: 3,
    officialAwayScore: 2,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'G',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'group_position',
    awaySourceGroupCode: 'H',
    awaySourceGroupRank: 2,
    awaySourceGroupSet: null,
    awaySourceMatchId: null
  },
  {
    id: '78',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'France',
    awayTeam: 'Denmark',
    homeTeamCode: 'FRA',
    awayTeamCode: 'DEN',
    kickoff: '30 jun 2026, 16:30',
    kickoffAt: '2026-06-30T16:30:00Z',
    stadium: 'Toronto Stadium',
    city: 'Toronto',
    status: 'finished',
    displayOrder: 78,
    officialHomeScore: 2,
    officialAwayScore: 1,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'I',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'best_third_place',
    awaySourceGroupCode: null,
    awaySourceGroupRank: 3,
    awaySourceGroupSet: 'ADGHI',
    awaySourceMatchId: null
  },
  {
    id: '79',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Spain',
    awayTeam: 'Croatia',
    homeTeamCode: 'ESP',
    awayTeamCode: 'CRO',
    kickoff: '1 jul 2026, 12:00',
    kickoffAt: '2026-07-01T12:00:00Z',
    stadium: 'Seattle Stadium',
    city: 'Seattle',
    status: 'finished',
    displayOrder: 79,
    officialHomeScore: 2,
    officialAwayScore: 0,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'J',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'group_position',
    awaySourceGroupCode: 'K',
    awaySourceGroupRank: 2,
    awaySourceGroupSet: null,
    awaySourceMatchId: null
  },
  {
    id: '80',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Portugal',
    awayTeam: 'Uruguay',
    homeTeamCode: 'POR',
    awayTeamCode: 'URU',
    kickoff: '1 jul 2026, 16:30',
    kickoffAt: '2026-07-01T16:30:00Z',
    stadium: 'Kansas City Stadium',
    city: 'Kansas City',
    status: 'finished',
    displayOrder: 80,
    officialHomeScore: 1,
    officialAwayScore: 0,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'L',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'best_third_place',
    awaySourceGroupCode: null,
    awaySourceGroupRank: 3,
    awaySourceGroupSet: 'CEJKL',
    awaySourceMatchId: null
  },
  {
    id: '81',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Belgium',
    awayTeam: 'Colombia',
    homeTeamCode: 'BEL',
    awayTeamCode: 'COL',
    kickoff: '2 jul 2026, 12:00',
    kickoffAt: '2026-07-02T12:00:00Z',
    stadium: 'San Francisco Bay Stadium',
    city: 'San Francisco Bay',
    status: 'finished',
    displayOrder: 81,
    officialHomeScore: 1,
    officialAwayScore: 2,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'M',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'group_position',
    awaySourceGroupCode: 'N',
    awaySourceGroupRank: 2,
    awaySourceGroupSet: null,
    awaySourceMatchId: null
  },
  {
    id: '82',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Italy',
    awayTeam: 'South Korea',
    homeTeamCode: 'ITA',
    awayTeamCode: 'KOR',
    kickoff: '2 jul 2026, 16:30',
    kickoffAt: '2026-07-02T16:30:00Z',
    stadium: 'Philadelphia Stadium',
    city: 'Philadelphia',
    status: 'finished',
    displayOrder: 82,
    officialHomeScore: 2,
    officialAwayScore: 1,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'O',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'best_third_place',
    awaySourceGroupCode: null,
    awaySourceGroupRank: 3,
    awaySourceGroupSet: 'FGMNO',
    awaySourceMatchId: null
  },
  {
    id: '83',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Nigeria',
    awayTeam: 'Senegal',
    homeTeamCode: 'NGA',
    awayTeamCode: 'SEN',
    kickoff: '3 jul 2026, 12:00',
    kickoffAt: '2026-07-03T12:00:00Z',
    stadium: 'Monterrey Stadium',
    city: 'Monterrey',
    status: 'finished',
    displayOrder: 83,
    officialHomeScore: 0,
    officialAwayScore: 1,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'P',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'group_position',
    awaySourceGroupCode: 'Q',
    awaySourceGroupRank: 2,
    awaySourceGroupSet: null,
    awaySourceMatchId: null
  },
  {
    id: '84',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Sweden',
    awayTeam: 'Poland',
    homeTeamCode: 'SWE',
    awayTeamCode: 'POL',
    kickoff: '3 jul 2026, 16:30',
    kickoffAt: '2026-07-03T16:30:00Z',
    stadium: 'Boston Stadium',
    city: 'Boston',
    status: 'finished',
    displayOrder: 84,
    officialHomeScore: 1,
    officialAwayScore: 2,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'R',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'best_third_place',
    awaySourceGroupCode: null,
    awaySourceGroupRank: 3,
    awaySourceGroupSet: 'HIRPQ',
    awaySourceMatchId: null
  },
  {
    id: '85',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Chile',
    awayTeam: 'Ecuador',
    homeTeamCode: 'CHI',
    awayTeamCode: 'ECU',
    kickoff: '4 jul 2026, 12:00',
    kickoffAt: '2026-07-04T12:00:00Z',
    stadium: 'Guadalajara Stadium',
    city: 'Guadalajara',
    status: 'finished',
    displayOrder: 85,
    officialHomeScore: 2,
    officialAwayScore: 1,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'S',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'group_position',
    awaySourceGroupCode: 'T',
    awaySourceGroupRank: 2,
    awaySourceGroupSet: null,
    awaySourceMatchId: null
  },
  {
    id: '86',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Norway',
    awayTeam: 'Canada',
    homeTeamCode: 'NOR',
    awayTeamCode: 'CAN',
    kickoff: '4 jul 2026, 16:30',
    kickoffAt: '2026-07-04T16:30:00Z',
    stadium: 'Atlanta Stadium',
    city: 'Atlanta',
    status: 'finished',
    displayOrder: 86,
    officialHomeScore: 0,
    officialAwayScore: 1,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'U',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'best_third_place',
    awaySourceGroupCode: null,
    awaySourceGroupRank: 3,
    awaySourceGroupSet: 'LMSTU',
    awaySourceMatchId: null
  },
  {
    id: '87',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Australia',
    awayTeam: 'Turkey',
    homeTeamCode: 'AUS',
    awayTeamCode: 'TUR',
    kickoff: '5 jul 2026, 12:00',
    kickoffAt: '2026-07-05T12:00:00Z',
    stadium: 'Dallas Stadium',
    city: 'Dallas',
    status: 'finished',
    displayOrder: 87,
    officialHomeScore: 1,
    officialAwayScore: 2,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'V',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'group_position',
    awaySourceGroupCode: 'W',
    awaySourceGroupRank: 2,
    awaySourceGroupSet: null,
    awaySourceMatchId: null
  },
  {
    id: '88',
    stage: 'round_of_32',
    group: 'Round of 32',
    groupCode: null,
    homeTeam: 'Croatia',
    awayTeam: 'Serbia',
    homeTeamCode: 'CRO',
    awayTeamCode: 'SRB',
    kickoff: '5 jul 2026, 16:30',
    kickoffAt: '2026-07-05T16:30:00Z',
    stadium: 'New York New Jersey Stadium',
    city: 'New York New Jersey',
    status: 'finished',
    displayOrder: 88,
    officialHomeScore: 2,
    officialAwayScore: 1,
    homeSourceType: 'group_position',
    homeSourceGroupCode: 'X',
    homeSourceGroupRank: 1,
    homeSourceGroupSet: null,
    homeSourceMatchId: null,
    awaySourceType: 'best_third_place',
    awaySourceGroupCode: null,
    awaySourceGroupRank: 3,
    awaySourceGroupSet: 'NOPVW',
    awaySourceMatchId: null
  },

  {
    id: '89',
    stage: 'round_of_16',
    group: 'Round of 16',
    groupCode: null,
    homeTeam: 'Mexico',
    awayTeam: 'Germany',
    homeTeamCode: 'MEX',
    awayTeamCode: 'GER',
    kickoff: '6 jul 2026, 17:00',
    kickoffAt: '2026-07-06T17:00:00Z',
    stadium: 'Dallas Stadium',
    city: 'Dallas',
    status: 'finished',
    displayOrder: 89,
    officialHomeScore: 1,
    officialAwayScore: 0,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '73',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '74'
  },
  {
    id: '90',
    stage: 'round_of_16',
    group: 'Round of 16',
    groupCode: null,
    homeTeam: 'Brazil',
    awayTeam: 'England',
    homeTeamCode: 'BRA',
    awayTeamCode: 'ENG',
    kickoff: '6 jul 2026, 21:00',
    kickoffAt: '2026-07-06T21:00:00Z',
    stadium: 'New York New Jersey Stadium',
    city: 'New York New Jersey',
    status: 'finished',
    displayOrder: 90,
    officialHomeScore: 2,
    officialAwayScore: 1,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '75',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '76'
  },
  {
    id: '91',
    stage: 'round_of_16',
    group: 'Round of 16',
    groupCode: null,
    homeTeam: 'Argentina',
    awayTeam: 'France',
    homeTeamCode: 'ARG',
    awayTeamCode: 'FRA',
    kickoff: '7 jul 2026, 17:00',
    kickoffAt: '2026-07-07T17:00:00Z',
    stadium: 'Miami Stadium',
    city: 'Miami',
    status: 'finished',
    displayOrder: 91,
    officialHomeScore: 2,
    officialAwayScore: 1,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '77',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '78'
  },
  {
    id: '92',
    stage: 'round_of_16',
    group: 'Round of 16',
    groupCode: null,
    homeTeam: 'Spain',
    awayTeam: 'Portugal',
    homeTeamCode: 'ESP',
    awayTeamCode: 'POR',
    kickoff: '7 jul 2026, 21:00',
    kickoffAt: '2026-07-07T21:00:00Z',
    stadium: 'Seattle Stadium',
    city: 'Seattle',
    status: 'finished',
    displayOrder: 92,
    officialHomeScore: 0,
    officialAwayScore: 1,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '79',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '80'
  },
  {
    id: '93',
    stage: 'round_of_16',
    group: 'Round of 16',
    groupCode: null,
    homeTeam: 'Colombia',
    awayTeam: 'Italy',
    homeTeamCode: 'COL',
    awayTeamCode: 'ITA',
    kickoff: '8 jul 2026, 17:00',
    kickoffAt: '2026-07-08T17:00:00Z',
    stadium: 'San Francisco Bay Stadium',
    city: 'San Francisco Bay',
    status: 'finished',
    displayOrder: 93,
    officialHomeScore: 0,
    officialAwayScore: 1,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '81',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '82'
  },
  {
    id: '94',
    stage: 'round_of_16',
    group: 'Round of 16',
    groupCode: null,
    homeTeam: 'Senegal',
    awayTeam: 'Poland',
    homeTeamCode: 'SEN',
    awayTeamCode: 'POL',
    kickoff: '8 jul 2026, 21:00',
    kickoffAt: '2026-07-08T21:00:00Z',
    stadium: 'Boston Stadium',
    city: 'Boston',
    status: 'finished',
    displayOrder: 94,
    officialHomeScore: 1,
    officialAwayScore: 2,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '83',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '84'
  },
  {
    id: '95',
    stage: 'round_of_16',
    group: 'Round of 16',
    groupCode: null,
    homeTeam: 'Chile',
    awayTeam: 'Canada',
    homeTeamCode: 'CHI',
    awayTeamCode: 'CAN',
    kickoff: '9 jul 2026, 17:00',
    kickoffAt: '2026-07-09T17:00:00Z',
    stadium: 'Atlanta Stadium',
    city: 'Atlanta',
    status: 'finished',
    displayOrder: 95,
    officialHomeScore: 1,
    officialAwayScore: 0,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '85',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '86'
  },
  {
    id: '96',
    stage: 'round_of_16',
    group: 'Round of 16',
    groupCode: null,
    homeTeam: 'Turkey',
    awayTeam: 'Croatia',
    homeTeamCode: 'TUR',
    awayTeamCode: 'CRO',
    kickoff: '9 jul 2026, 21:00',
    kickoffAt: '2026-07-09T21:00:00Z',
    stadium: 'New York New Jersey Stadium',
    city: 'New York New Jersey',
    status: 'finished',
    displayOrder: 96,
    officialHomeScore: 1,
    officialAwayScore: 2,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '87',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '88'
  },

  {
    id: '97',
    stage: 'quarterfinals',
    group: 'Quarterfinals',
    groupCode: null,
    homeTeam: 'Mexico',
    awayTeam: 'Brazil',
    homeTeamCode: 'MEX',
    awayTeamCode: 'BRA',
    kickoff: '10 jul 2026, 16:00',
    kickoffAt: '2026-07-10T16:00:00Z',
    stadium: 'Los Angeles Stadium',
    city: 'Los Angeles',
    status: 'finished',
    displayOrder: 97,
    officialHomeScore: 1,
    officialAwayScore: 1,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '89',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '90'
  },
  {
    id: '98',
    stage: 'quarterfinals',
    group: 'Quarterfinals',
    groupCode: null,
    homeTeam: 'Argentina',
    awayTeam: 'Italy',
    homeTeamCode: 'ARG',
    awayTeamCode: 'ITA',
    kickoff: '10 jul 2026, 20:00',
    kickoffAt: '2026-07-10T20:00:00Z',
    stadium: 'Miami Stadium',
    city: 'Miami',
    status: 'finished',
    displayOrder: 98,
    officialHomeScore: 2,
    officialAwayScore: 0,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '91',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '93'
  },
  {
    id: '99',
    stage: 'quarterfinals',
    group: 'Quarterfinals',
    groupCode: null,
    homeTeam: 'Portugal',
    awayTeam: 'Poland',
    homeTeamCode: 'POR',
    awayTeamCode: 'POL',
    kickoff: '11 jul 2026, 16:00',
    kickoffAt: '2026-07-11T16:00:00Z',
    stadium: 'Seattle Stadium',
    city: 'Seattle',
    status: 'finished',
    displayOrder: 99,
    officialHomeScore: 3,
    officialAwayScore: 1,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '92',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '94'
  },
  {
    id: '100',
    stage: 'quarterfinals',
    group: 'Quarterfinals',
    groupCode: null,
    homeTeam: 'Chile',
    awayTeam: 'Croatia',
    homeTeamCode: 'CHI',
    awayTeamCode: 'CRO',
    kickoff: '11 jul 2026, 20:00',
    kickoffAt: '2026-07-11T20:00:00Z',
    stadium: 'Atlanta Stadium',
    city: 'Atlanta',
    status: 'finished',
    displayOrder: 100,
    officialHomeScore: 1,
    officialAwayScore: 2,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '95',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '96'
  },

  {
    id: '101',
    stage: 'semifinals',
    group: 'Semifinals',
    groupCode: null,
    homeTeam: 'Mexico',
    awayTeam: 'Argentina',
    homeTeamCode: 'MEX',
    awayTeamCode: 'ARG',
    kickoff: '15 jul 2026, 19:00',
    kickoffAt: '2026-07-15T19:00:00Z',
    stadium: 'Atlanta Stadium',
    city: 'Atlanta',
    status: 'finished',
    displayOrder: 101,
    officialHomeScore: 0,
    officialAwayScore: 2,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '97',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '98'
  },
  {
    id: '102',
    stage: 'semifinals',
    group: 'Semifinals',
    groupCode: null,
    homeTeam: 'Portugal',
    awayTeam: 'Croatia',
    homeTeamCode: 'POR',
    awayTeamCode: 'CRO',
    kickoff: '16 jul 2026, 19:00',
    kickoffAt: '2026-07-16T19:00:00Z',
    stadium: 'Seattle Stadium',
    city: 'Seattle',
    status: 'finished',
    displayOrder: 102,
    officialHomeScore: 1,
    officialAwayScore: 2,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '99',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '100'
  },

  {
    id: '103',
    stage: 'third_place',
    group: 'Third place',
    groupCode: null,
    homeTeam: 'Mexico',
    awayTeam: 'Portugal',
    homeTeamCode: 'MEX',
    awayTeamCode: 'POR',
    kickoff: '18 jul 2026, 15:00',
    kickoffAt: '2026-07-18T15:00:00Z',
    stadium: 'Boston Stadium',
    city: 'Boston',
    status: 'scheduled',
    displayOrder: 103,
    officialHomeScore: null,
    officialAwayScore: null,
    homeSourceType: 'match_loser',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '101',
    awaySourceType: 'match_loser',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '102'
  },
  {
    id: '104',
    stage: 'final',
    group: 'Final',
    groupCode: null,
    homeTeam: 'Argentina',
    awayTeam: 'Croatia',
    homeTeamCode: 'ARG',
    awayTeamCode: 'CRO',
    kickoff: '19 jul 2026, 18:00',
    kickoffAt: '2026-07-19T18:00:00Z',
    stadium: 'New York New Jersey Stadium',
    city: 'New York New Jersey',
    status: 'scheduled',
    displayOrder: 104,
    officialHomeScore: null,
    officialAwayScore: null,
    homeSourceType: 'match_winner',
    homeSourceGroupCode: null,
    homeSourceGroupRank: null,
    homeSourceGroupSet: null,
    homeSourceMatchId: '101',
    awaySourceType: 'match_winner',
    awaySourceGroupCode: null,
    awaySourceGroupRank: null,
    awaySourceGroupSet: null,
    awaySourceMatchId: '102'
  }
];
